# This is a basic workflow to help you get started with Actions

name: Oracle

on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
         node-version: 16
         
      - name: Install dependencies
      - run: ./npm install
      
      - name: Build with npm
      - run: ./npm run build
       
      - name: Set up QEMU
      - uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
      - uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: stefanofrontini/spesa:latest



